books/urls.py
from django.conf.urls import include, url
from books import views

urlpatterns = [
    url(r'^$', views.BooksModelView.as_view(), name='index'),

    url(r'^book/$', views.BookList.as_view(), name='book_list'),
    url(r'^author/$', views.AuthorList.as_view(), name='author_list'),
    url(r'^publisher/$', views.PublisherList.as_view(), name='publisher_list'),

    url(r'^book/(?P<pk>\d+)/$', views.BookDetail.as_view(), name='book_detail'),
    url(r'^author/(?P<pk>\d+)/$', views.AuthorDetail.as_view(), name='author_detail'),
    url(r'^publisher/(>P<pk>\d+)/$', views.PublisherDetail.as_view(), name='publisher_detail')
]

polls/urls.py
from django.conf.urls import url
from polls import views

urlpatterns = [

    # Example: /polls/
    url(r'^$', views.index, name='index'),
    # Example: /polls/1/
    url(r'^(?P<question_id>\d+)/$', views.detail, name='detail'),
    # Example: /polls/1/vote
    url(r'^(?P<question_id>\d+)/vote/$', views.vote, name='vote'),
    # Example: /polls/1/result
    url(r'^(?P<question_id>\d+)/result/$', views.result, name='result'),
]

tutorial/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^polls/', include('polls.urls', namespace='polls')),
    url(r'^books/', include('books.urls', namespace='books')),
]

polls/models.py
from django.db import models

# Create your models here.

class Question(models.Model):
    question_text = models.CharField('QUESTION_TEST', max_length=200)
    pub_date = models.DateTimeField('PUBLISHED DATE')

    def __str__(self):
        return self.question_text

class Choice(models.Model):
    question = models.ForeignKey('QUESTION', Question)
    choice_text = models.CharField('CHOICE_TEXT', max_length=200)
    votes = models.IntegerField('VOTES', default=0)

    def __str__(self):
        return self.choice_text

polls/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from polls.models import Question, Choice

# Create your views here.

def index(request):
    latest_question_list = Question.objects.all().order_by('-pub_date')[:5]
    context = {'latest_question_list': latest_question_list}
    return render(request, 'index.html', context)

def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'detail.html', {'question' : question})

def vote(request, question_id):
    p = get_object_or_404(Question, pk=question_id)

    try:
        selected_choice = p.choice_set.get(pk=request.POST['choice'])
    except(KeyError, Choice.DoesNoeExist):
        return render(request, 'detail.html', {
            'question':p,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('polls:result', args=(p.id,)))

def result(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'result.html', {'question': question})

books/templates/author_detail.html
{% extends "base_books.html" %}

{% block content %}
    <h1>{{object.name}}</h1>
    <p>{{object.salutation}}</p>
    <li>Email: {{object.email}}</li>
{% endblock content%}

books/templates/author_list.html
{% extends "base_books.html" %}

{% block content %}
    <h2>Author List</h2>
    <ul>
        {% for author in object_list %}
            <li>
                <a href="{% url 'books:author_detail' author.id %}">{{author.name}}</a>
            </li>
        {% endfor %}
    </ul>
{% endblock content %}

books/templates/book_detail.html
{% extends "base_books.html" %}

{% block content %}
    <h1>{{object.title}}</h1>
    <br/>
    <li>
        Authors:
        {% for author in object.authors.all %}
            {{author}}
            {% if not forloop.last %},
            {% else %}
            {%endif%}
        {% endfor %}
    </li>
    <li> Publisher: {{object.publisher}} </li>
    <li> Publication date: {{object.publication_date}} </li>
{% endblock content %}

books/templates/book_list.html
{% extends "base_books.html" %}

{% block content %}
    <h2>Book List</h2>
    <ul>
        {% for book in object_list %}
            <li>
                <a href="{% url 'books:book_detail' book.id %}">{{book.title}}</a>
            </li>
        {% endfor %}
    </ul>
{% endblock content %}

books/templates/index.html
{% extends "base_books.html" %}

{% block content %}
    <h2>Books Management System</h2>
    <ul>
        {% for modelname in object_list %}
            {% with "books:"|add:modelname|lower|add:"_list" as urlvar %}
            <li>
                <a href="{% url urlvar %}">{{modelname}}</a>
            </li>
            {%endwith%}
        {%endfor%}
    </ul>
{% endblock content %}

books/templates/publisher_detail.html
{% extends "base_books.html" %}

{% block content %}
    <h1>{{object.name}}</h1>
    <p>{{object.website}}</p>
    <li>Address: {{object.address}}</li>
{% endblock content%}

books/templates/publisher_list.html
{% extends "base_books.html" %}

{% block content %}
    <h2>Publisher List</h2>
    <ul>
        {% for publisher in object_list %}
            <li>
                <a href="{% url 'books:publisher_detail' publisher.id %}">{{publisher.name}}</a>
            </li>
        {% endfor %}
    </ul>
{% endblock content %}

polls/templates/detail.html
<h1>{{question.question_text}}</h1>
{% if error_message %}
    <p><strong>{{error_message}}</strong></p>
{% endif %}

<form action="{%url 'polls:vote' question.id %}" method="post">
    {% csrf_token %}
    {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{forloop.counter}}" value="{{choice.id}}"/>
        <label for="choice{{forloop.counter}}">{{choice.choice_text}}</label><br/>
    {% endfor %}
    <input type="submit" value="Vote"/>
</form>

polls/templates/index.html
{% if latest_question_list %}
    <ul>
        {% for question in latest_question_list %}
            <li><a href="/polls/{{question.id}}">{{question.question_text}}</a></li>
        {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

polls/templates/result.html
<h1>{{ question.question_text }}</h1>

<ul>
    {% for choice in question.choice_set.all%}
        <li>
            {{choice.choice_text}} - {{choice.votes}} vote{{choice.votes|pluralize}}
        </li>
    {% endfor %}
</ul>

<a href="{%url 'polls:detail' question.id %}">Vote again?</a>

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load static %}
    <link rel="stylesheet"/>
    <title>{%block title%}My Amazing Site{%end block%}</title>
</head>
<body>
    <div id="sidebar">
        {% block sidebar %}
            <ul>
                <li><a href="/">Project_Home</a></li>
                <li><a href="/admin/">Admin</a> </li>
            </ul>
        {% endblock %}
        <br/>
    </div>

    <div id="content">
        {% block content %}{% endblock %}
    </div>
</body>
</html>

templates/base_books.html
{% extends "base.html" %}

<title>{% block title %}Books Application Site{% endblock %}</title>

{% block sidebar %}
    {{block.super}}
    <ul>
        <li> <a href="/books/">Books_Home</a></li>
    </ul>
{% endblock%}